In [0]:
import pandas as pd

In [0]:
url_data = [['www.yahoo.com', 1],
            ['google.com', 1],
            ['http://google.com', 1],
            ['http://oogle.com', 0],
            ['http://google.com/a.html', 0],
            ['ggle.net', 0],
            ['www.yahoo.com/', 2],
            ['google.com/', 2],
            ['http://google.com/', 2],
            ['http://oogle.com/', 0],
            ['http://google.com/a.html/', 1],
            ['ggle.net/', 2]
            ]
url_columns = ['url', 'label']

In [0]:
pd.DataFrame??

In [4]:
df_url = pd.DataFrame(data=url_data, columns=url_columns)
df_url.head()

url  label
0             www.yahoo.com      1
1                google.com      1
2         http://google.com      1
3          http://oogle.com      0
4  http://google.com/a.html      0

In [5]:
#count number of dots
symbols = {'dots':'.', 'slashes':'/'}

for s in symbols:
  print s, symbols[s]
  df_url[s] = df_url['url'].apply(lambda x: x.count(symbols[s]))

df_url['len'] = df_url['url'].apply(lambda x: len(x))
display(df_url)

dots .
slashes /


url  label  dots  slashes  len
0               www.yahoo.com      1     2        0   13
1                  google.com      1     1        0   10
2           http://google.com      1     1        2   17
3            http://oogle.com      0     1        2   16
4    http://google.com/a.html      0     2        3   24
5                    ggle.net      0     1        0    8
6              www.yahoo.com/      2     2        1   14
7                 google.com/      2     1        1   11
8          http://google.com/      2     1        3   18
9           http://oogle.com/      0     1        3   17
10  http://google.com/a.html/      1     2        4   25
11                  ggle.net/      2     1        1    9

In [6]:
df_url.describe()

label       dots    slashes        len
count  12.000000  12.000000  12.000000  12.000000
mean    1.000000   1.333333   1.666667  15.166667
std     0.852803   0.492366   1.370689   5.474459
min     0.000000   1.000000   0.000000   8.000000
25%     0.000000   1.000000   0.750000  10.750000
50%     1.000000   1.000000   1.500000  15.000000
75%     2.000000   2.000000   3.000000  17.250000
max     2.000000   2.000000   4.000000  25.000000

In [7]:
X = df_url.drop(['label','url'], axis = 'columns')
y = df_url['label']
display(X, y )

dots  slashes  len
0      2        0   13
1      1        0   10
2      1        2   17
3      1        2   16
4      2        3   24
5      1        0    8
6      2        1   14
7      1        1   11
8      1        3   18
9      1        3   17
10     2        4   25
11     1        1    9

0     1
1     1
2     1
3     0
4     0
5     0
6     2
7     2
8     2
9     0
10    1
11    2
Name: label, dtype: int64

In [0]:
RAND_SEED = 33

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = RAND_SEED)

In [9]:
display(X_train, X_test, y_train, y_test)

dots  slashes  len
10     2        4   25
3      1        2   16
6      2        1   14
1      1        0   10
9      1        3   17
2      1        2   17
8      1        3   18
7      1        1   11
4      2        3   24

dots  slashes  len
0      2        0   13
11     1        1    9
5      1        0    8

10    1
3     0
6     2
1     1
9     0
2     1
8     2
7     2
4     0
Name: label, dtype: int64

0     1
11    2
5     0
Name: label, dtype: int64

# Machine Learning

In [0]:
# use baseline classifiers that do not require standardisation
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBClassifier

models = {'Logistic Regression': LogisticRegression(),
          'Naive Bayes':GaussianNB(),
          'Decision Tree': DecisionTreeClassifier(),
          'AdaBoost': AdaBoostClassifier(),
          'Gradient Boosting': GradientBoostingClassifier(),
          'XGBoost': XGBClassifier(),
          'Random Forest': RandomForestClassifier()
          }

In [0]:
from sklearn.metrics import f1_score, classification_report, confusion_matrix

In [0]:
f1_score??

In [13]:
f1 = {}
cr = {}
cm = {}

for m in models:
  clf = models[m]
  clf.fit(X_train, y_train)
  pred = clf.predict(X_test)
  f1[m] = '{0:.2f}'.format(f1_score(y_test, pred, average='macro'))
  cr[m] = classification_report(y_test, pred)
  cm[m] = confusion_matrix(y_test, pred)

  print '\nPrediction for', m, pred
  print 'F1 score', f1[m]
  print cr[m]
  print cm[m]

/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)



Prediction for Decision Tree [1 2 1]
F1 score 0.56
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1
           2       1.00      1.00      1.00         1

   micro avg       0.67      0.67      0.67         3
   macro avg       0.50      0.67      0.56         3
weighted avg       0.50      0.67      0.56         3

[[0 1 0]
 [0 1 0]
 [0 0 1]]

Prediction for XGBoost [2 2 2]
F1 score 0.17
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           2       0.33      1.00      0.50         1

   micro avg       0.33      0.33      0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3

[[0 0 1]
 [0 0 1]
 [0 0 1]]

Prediction for Naive Bayes [2 2 1]
F1 score 0.22
              precision    recall 

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


# Neural Network

In [14]:
X_train.shape[1]

3

In [15]:
from keras.layers import Dense
from keras.models import Sequential

def build_nn(n):
  model = Sequential()
  model.add(Dense(units=32, input_dim=n, activation='relu'))
  model.add(Dense(units=16, activation='relu'))
  model.add(Dense(units=3,activation='softmax'))

  model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
  model.summary()

  return model

nn_model = build_nn(X_train.shape[1])
nn_model.fit(X_train, y_train, epochs=100, verbose=0, validation_split=0.2)
pred = nn_model.predict_classes(X_test)
f1 = '{0:.3f}'.format(f1_score(y_test,pred, average='macro'))
cm = confusion_matrix(y_test, pred)
cr = classification_report(y_test,pred)
print 'Neural Network f1-score: ', f1
print cr
print cm

Using TensorFlow backend.
W0918 13:33:24.644325 140169749440384 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0918 13:33:24.658576 140169749440384 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0918 13:33:24.661514 140169749440384 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0918 13:33:24.698620 140169749440384 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0918 13:33:24.719331 14016974

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                128       
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 51        
Total params: 707
Trainable params: 707
Non-trainable params: 0
_________________________________________________________________


W0918 13:33:24.947124 140169749440384 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Neural Network f1-score:  0.167
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.33      1.00      0.50         1
           2       0.00      0.00      0.00         1

   micro avg       0.33      0.33      0.33         3
   macro avg       0.11      0.33      0.17         3
weighted avg       0.11      0.33      0.17         3

[[0 1 0]
 [0 1 0]
 [0 1 0]]


# LSTM

In [16]:
# process sequences for LSTM
def convert(url):
  results = []

  for i in range(len(url)):
    results.append(ord(url[i]))

  return results

convert('xyz')

[120, 121, 122]

In [17]:
df_url['sequence'] = df_url['url'].apply(lambda x: convert(x))
display(df_url)

url  ...                                           sequence
0               www.yahoo.com  ...  [119, 119, 119, 46, 121, 97, 104, 111, 111, 46...
1                  google.com  ...   [103, 111, 111, 103, 108, 101, 46, 99, 111, 109]
2           http://google.com  ...  [104, 116, 116, 112, 58, 47, 47, 103, 111, 111...
3            http://oogle.com  ...  [104, 116, 116, 112, 58, 47, 47, 111, 111, 103...
4    http://google.com/a.html  ...  [104, 116, 116, 112, 58, 47, 47, 103, 111, 111...
5                    ggle.net  ...            [103, 103, 108, 101, 46, 110, 101, 116]
6              www.yahoo.com/  ...  [119, 119, 119, 46, 121, 97, 104, 111, 111, 46...
7                 google.com/  ...  [103, 111, 111, 103, 108, 101, 46, 99, 111, 10...
8          http://google.com/  ...  [104, 116, 116, 112, 58, 47, 47, 103, 111, 111...
9           http://oogle.com/  ...  [104, 116, 116, 112, 58, 47, 47, 111, 111, 103...
10  http://google.com/a.html/  ...  [104, 116, 116, 112, 58, 47, 47, 103, 111, 111...
11                  ggle.net/  ...        [103, 103, 108, 101, 46, 110, 101, 116, 47]

[12 rows x 6 columns]

In [0]:
X = df_url['sequence']

from keras.preprocessing.sequence import pad_sequences

pad_sequences??

In [19]:
N_STEPS = 20
N_FEATURES = 1

X = pad_sequences(X, maxlen=N_STEPS, padding='post', truncating='post')
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=RAND_SEED)
display(X)

array([[119, 119, 119,  46, 121,  97, 104, 111, 111,  46,  99, 111, 109,
          0,   0,   0,   0,   0,   0,   0],
       [103, 111, 111, 103, 108, 101,  46,  99, 111, 109,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [104, 116, 116, 112,  58,  47,  47, 103, 111, 111, 103, 108, 101,
         46,  99, 111, 109,   0,   0,   0],
       [104, 116, 116, 112,  58,  47,  47, 111, 111, 103, 108, 101,  46,
         99, 111, 109,   0,   0,   0,   0],
       [104, 116, 116, 112,  58,  47,  47, 103, 111, 111, 103, 108, 101,
         46,  99, 111, 109,  47,  97,  46],
       [103, 103, 108, 101,  46, 110, 101, 116,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [119, 119, 119,  46, 121,  97, 104, 111, 111,  46,  99, 111, 109,
         47,   0,   0,   0,   0,   0,   0],
       [103, 111, 111, 103, 108, 101,  46,  99, 111, 109,  47,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [104, 116, 116, 112,  58,  47,  47, 103, 111, 111, 103, 1

In [0]:
from keras.layers import LSTM, Dense, Masking
from keras.models import Sequential

In [0]:
LSTM??

In [0]:
def build_LSTM(input_shape):
  model = Sequential()
  model.add(Masking(input_shape=input_shape)) # masking helps
  model.add(LSTM(units=32,activation='relu', return_sequences=True))
  model.add(LSTM(units=32, activation='relu', return_sequences=False))
  model.add(Dense(units=3, activation='softmax')) # instead of 1 unit sigmoid for binary class

  # model.compile(optimizer='adam', loss='categorical_crossentropy') # for one-hot
  # model.compile(optimizer='adam', loss='binary_crossentropy') # for 2 classes
  model.compile(optimizer='adam', loss='sparse_categorical_crossentropy') # for multi class
  
  model.summary()

  return model

In [23]:
model = build_LSTM((N_STEPS, N_FEATURES))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
masking_1 (Masking)          (None, 20, 1)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 20, 32)            4352      
_________________________________________________________________
lstm_2 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 99        
Total params: 12,771
Trainable params: 12,771
Non-trainable params: 0
_________________________________________________________________


In [24]:
NB_EPOCHS = 500

X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], N_FEATURES)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], N_FEATURES)

model.fit(X_train, y_train, epochs=NB_EPOCHS, validation_split=0.2,verbose=0)
pred = model.predict_classes(X_test) # instead of predict

f1 = '{0:.3f}'.format(f1_score(y_test, pred, average='macro'))
cm = confusion_matrix(y_test,pred)
cr = classification_report(y_test, pred)

print f1, cm, cr

0.556 [[0 1 0]
 [0 1 0]
 [0 0 1]]               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1
           2       1.00      1.00      1.00         1

   micro avg       0.67      0.67      0.67         3
   macro avg       0.50      0.67      0.56         3
weighted avg       0.50      0.67      0.56         3

